global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bolt-node'
    static_configs:
      - targets: ['bolt:7336']
        labels:
          network: 'testnet'
          
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']